revisions to term request guide
OBOAcademy/obook pull request #198
Opened 2022-06-30 13:10 UTC by nicolevasilevsky

- move doc to 'how to' folder

address #187

2022-07-02 15:01 UTC, matentzn requested changes
Thank you @nicolevasilevsky!

Dont forget to update mkdocs.yaml

2022-07-05 18:27 UTC, nicolevasilevsky commented on docs/howto/term-request.md
> +- [OntoTips](https://douroucouli.wordpress.com/category/tutorials/) - A guide by Chris Mungall covering various aspects of ontology engineering.
done

2022-07-05 18:27 UTC, nicolevasilevsky commented
> Dont forget to update mkdocs.yaml

done

2022-07-05 19:37 UTC, matentzn approved these changes

2022-07-06 00:08 UTC, merged