Taxon constraints update
OBOAcademy/obook pull request #329
Opened 2023-01-10 04:15 UTC by balhoff

2023-01-10 08:51 UTC, shawntanzk commented on docs/explanation/taxon-constraints-explainer.md
> +## How to add taxon restrictions:
Could I suggest we move this up to before `## Using taxon restrictions for Quality Control` - I understand the logic of doing it this way, but I'm thinking more on the side of an ontology editor which might get intimidated by the new additions. Would like to funnel them into the how-to before that happens and all.

2023-01-10 08:51 UTC, shawntanzk requested changes
This is awesome! love the mermaid graphs :D Just added a suggestion to move a section up. Thanks!

2023-01-11 18:24 UTC, balhoff commented
I think this is ready to merge.

2023-01-12 12:43 UTC, matentzn commented
@shawntanzk I will let you merge this!

2023-01-12 13:08 UTC, shawntanzk commented
Looks good, thanks so much @balhoff - learnt so much from this :)

2023-01-12 13:08 UTC, merged